spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true

jwt-token:
  secret-key: jwtFSEvgSvfsevGe43ybt7gupbhxfFDgvsbjnidt21rt7kkfhjreryhx
  durability: 3600000