name: Deploy Test
run-name: ${{ github.actor }} <- tester
on: workflow_dispatch
env:
  REGISTRY: ghcr.io
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          #password: ${{ secrets.DOCKER_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:src/main/docker"
          push: true
          tags: latest #ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/my-image:${{ github.sha }}

